### ISSUE TITLE
Any replay protection?

### ISSUE THREAD

**Issue by ghost** [bitcoincashplus/bitcoincashplus#32]
Is there any replay protection integrated?

Seems there is no replay protection against bitcoin cash..,..

**Comment by Ayms** [comment]
Indeed, there are none, please see https://github.com/Ayms/bitcoin-transactions/issues/20

**Comment by bitcoincashplus** [comment]
There is 2-way Replay protection (SIGHASH_FORK_ID). Our fork is from bitcoin not BCH

**Comment by Ayms** [comment]
You have the same replay protection than BCH, which makes possible to replay transactions on BCH (ie for coins not moved after the BCH fork)
