### ISSUE TITLE
WARNING! Malware

### ISSUE THREAD

**Issue by mnemotiv** [bitcoincashplus/bitcoincashplus#38]
windows wallet is infected

![image](https://user-images.githubusercontent.com/3081042/36590900-da932aea-1898-11e8-88a1-33deffa3f9c0.png)

**Comment by bitcoincashplus** [comment]
windows defender or some anti-virus software sometimes can detect mining software as threat you need to add it to trusted list. You can exe file scan here https://virusdesk.kaspersky.com/
